apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base

replicas:
  - name: devops-app
    count: 3

images:
  - name: shivamyd/devops-app
    newTag: 1.0.0

patches:
  - target:
      kind: Deployment
      name: devops-app
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: production
