apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qa

resources:
  - ../../base
  - ingress.yaml

replicas:
  - name: devops-app
    count: 2

images:
  - name: 845430216465.dkr.ecr.us-east-1.amazonaws.com/devops-app:1.0.0
    #    newTag: IMAGE_TAG_PLACEHOLDER

patches:
  - target:
      kind: Deployment
      name: devops-app
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: qa
