name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: ${{ vars.FORCE_JAVASCRIPT_ACTIONS_TO_NODE24 }}
  
jobs:

  test:
    runs-on: [self-hosted, linux, k3s]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check Python
        run: python3 --version

      - name: Create virtual environment
        run: python3 -m venv venv

      - name: Install dependencies
        run: |
          ./venv/bin/pip install --upgrade pip
          ./venv/bin/pip install -r app/requirements.txt

      - name: Test application
        run: |
          ./venv/bin/python -m py_compile app/app.py

  docker:
    needs: test

    runs-on: [self-hosted, linux, k3s]

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build \
            -t 845430216465.dkr.ecr.us-east-1.amazonaws.com/devops-app:${{ github.sha }} \
            ./app

      - name: Push Docker image
        run: |
          docker push \
            845430216465.dkr.ecr.us-east-1.amazonaws.com/devops-app:${{ github.sha }}

  deploy-qa:
    needs: docker

    runs-on: [self-hosted, linux, k3s]
    
    environment:
      name: qa
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Deploy to QA
        run: |
          kubectl kustomize kubernetes/environments/qa \
            | sed "s|IMAGE_TAG_PLACEHOLDER|${{ github.sha }}|g" \
            | kubectl apply -f -

      - name: Restart QA deployment
        run: |
          kubectl rollout restart \
            deployment/devops-app \
            -n qa

      - name: Wait for deployment
        run: |
          kubectl rollout status \
            deployment/devops-app \
            -n qa \
            --timeout=500s    
          
      - name: Check QA pods
        run: |
          kubectl get pods -n qa

      - name: Check QA service
        run: |
          kubectl get service -n qa

      - name: Verify QA image
        run: |
         kubectl get deployment devops-app \
            -n qa \
            -o jsonpath='{.spec.template.spec.containers[0].image}'
            echo



  deploy-uat:
    needs: deploy-qa 

    runs-on: [self-hosted, linux, k3s]

    environment:
      name: uat

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Deploy to UAT
        run: |
          kubectl kustomize kubernetes/environments/uat \
            | sed "s|IMAGE_TAG_PLACEHOLDER|${{ github.sha }}|g" \
            | kubectl apply -f -

      - name: Wait for UAT deployment
        run: |
          kubectl rollout status \
            deployment/devops-app \
            -n uat \
            --timeout=120s

      - name: Check UAT pods
        run: |
          kubectl get pods -n uat

      - name: Check UAT service
        run: |
          kubectl get service -n uat

      - name: Verify UAT image
        run: |
          kubectl get deployment devops-app \
            -n uat \
            -o jsonpath='{.spec.template.spec.containers[0].image}'
            echo

      - name: UAT health check
        run: |
          kubectl run uat-health-check \
          --rm \
          -i \
          --restart=Never \
          -n uat \
          --image=curlimages/curl \
          -- \
          curl -f http://devops-app:5000/health

         
  deploy-production:
    needs: deploy-uat

    runs-on: [self-hosted, linux, k3s]

    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Deploy to Production
        run: |
          kubectl kustomize kubernetes/environments/production \
            | sed "s|IMAGE_TAG_PLACEHOLDER|${{ github.sha }}|g" \
            | kubectl apply -f -

      - name: Wait for Production rollout
        run: |
          kubectl rollout status \
            deployment/devops-app \
            -n production \
            --timeout=120s

      - name: Check Production pods
        run: |
          kubectl get pods -n production

      - name: Check Production service
        run: |
          kubectl get service -n production

      - name: Verify Production image
        run: |
          kubectl get deployment devops-app \
            -n production \
            -o jsonpath='{.spec.template.spec.containers[0].image}'
            echo
      - name: Production health check
        run: |
          kubectl run production-health-check \
          --rm \
          -i \
          --restart=Never \
          -n production \
          --image=curlimages/curl \
          -- \
          curl -f http://devops-app:5000/health

      - name: Deployment summary
        run: |
         echo "Application deployed successfully"
         echo "Environment: production"
         echo "Image: ${{ secrets.DOCKERHUB_USERNAME }}/devops-app:${{ github.sha }}"
