name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  test:
    runs-on: [self-hosted, linux, k3s]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Python
        run: python3 --version

      - name: Create virtual environment
        run: python3 -m venv venv

      - name: Install dependencies
        run: |
          ./venv/bin/pip install --upgrade pip
          ./venv/bin/pip install -r app/requirements.txt

      - name: Test application
        run: |
          ./venv/bin/python -m py_compile app/app.py


  docker:
    needs: test

    runs-on: [self-hosted, linux, k3s]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-app:${{ github.sha }} \
            ./app

      - name: Push Docker image
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/devops-app:${{ github.sha }}


  deploy-qa:
    needs: docker

    runs-on: [self-hosted, linux, k3s]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to QA
        run: |
          kubectl kustomize kubernetes/environments/qa \
            | sed "s|IMAGE_TAG_PLACEHOLDER|${{ github.sha }}|g" \
            | kubectl apply -f -

      - name: Wait for deployment
        run: |
          kubectl rollout status \
            deployment/devops-app \
            -n qa \
            --timeout=120s

      - name: Check QA pods
        run: |
          kubectl get pods -n qa

      - name: Check QA service
        run: |
          kubectl get service -n qa
